# Generated by Django 4.1.5 on 2023-01-17 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_upload",
            field=models.FileField(
                null=True,
                upload_to="uploads/videos",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov"]
                    )
                ],
            ),
        ),
    ]
