# Generated by Django 4.1.5 on 2023-01-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_videomodel_creator_delete_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofile",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
