# Generated by Django 4.1.5 on 2023-01-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_video_duration"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="duration",),
    ]
