# Generated by Django 4.1.5 on 2023-01-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_video_duration"),
    ]

    operations = [
        migrations.RenameModel(old_name="Video", new_name="VideoModel",),
    ]
