# Generated by Django 4.1.5 on 2023-02-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_cronjoblock_cronjoblog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=4)),
            ],
        ),
    ]
